import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  controlsSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: '#f8f8f8',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e6e6e6',
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 9,
    fontSize: 13,
    color: '#111',
  },
  clearButton: {
    padding: 4,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
    marginTop: 8,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    marginBottom: 9,
  },
  filterButtonActive: {
    borderColor: '#7c3aed',
    backgroundColor: '#f3f0ff',
  },
  filterButtonText: {
    flex: 1,
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
    marginLeft: 8,
  },
  filterButtonTextActive: {
    color: '#7c3aed',
    fontWeight: '600',
  },
  activeFiltersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 9,
    marginTop: 6,
  },
  activeFilter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#f3f0ff',
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e9d5ff',
  },
  activeFilterText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7c3aed',
    textTransform: 'capitalize',
  },
  removeFilterButton: {
    padding: 2,
  },
  clearFiltersText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7c3aed',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    marginBottom: 6,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 9,
    paddingHorizontal: 6,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
  },
  actionButtonActive: {
    borderColor: '#7c3aed',
    backgroundColor: '#f3f0ff',
  },
  actionButtonText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666',
  },
  actionButtonTextActive: {
    color: '#7c3aed',
  },
  actionButtonDisabled: {
    opacity: 0.5,
    borderColor: '#e6e6e6',
  },
  actionButtonTextDisabled: {
    color: '#ccc',
  },
  list: {
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 100,
  },
  row: {
    gap: 8,
  },
  item: {
    flex: 1,
    marginBottom: 8,
  },
  skeletonItem: {
    opacity: 0.6,
  },
  skeletonCard: {
    height: 160,
    borderRadius: 14,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    padding: 11,
  },
  skeletonHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 10,
  },
  skeletonName: {
    height: 36,
    flex: 1,
    borderRadius: 8,
  },
  skeletonPrice: {
    width: 56,
    height: 18,
    borderRadius: 999,
  },
  skeletonCategory: {
    width: 88,
    height: 22,
    borderRadius: 8,
    marginBottom: 10,
  },
  skeletonRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  skeletonRatingIcon: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  skeletonRatingValue: {
    width: 70,
    height: 12,
    borderRadius: 6,
  },
  skeletonEditButtonWrap: {
    marginTop: 'auto',
    alignItems: 'flex-end',
  },
  skeletonEditButton: {
    width: 84,
    height: 30,
    borderRadius: 9,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 13,
    color: '#888',
    marginTop: 6,
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingBottom: 0,
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 24,
    maxHeight: '85%',
    overflow: 'hidden',
  },
  modalOptions: {
    maxHeight: 400,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
  },
  categoryOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  categoryOptionText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#111',
    textTransform: 'capitalize',
  },
})